apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: books-ingress
  namespace: books-api-development
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-stage"
    #external-dns.alpha.kubernetes.io/hostname: cryptoapp.neamulkabiremon.com
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - books.35.255.220.46.nip.io
      secretName: crypto-cert-staging
    # - hosts:
    #     - cryptoapp.neamulkabiremon.com
    #   secretName: crypto-cert
  rules:
    # - host: cryptoapp.neamulkabiremon.com
    - host: books.35.255.220.46.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: books-service
                port:
                  number: 80