apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: books-go-api-doppler-secret
  namespace: doppler-operator-system
spec:
  project: books-go-api
  config: dev
  tokenSecret:
    name: doppler-token-books-go-api
  managedSecret:
    name: books-go-api-secret
    namespace: books-api-development
